//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace billrda.RDA_TH {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RDAIBServiceSoap", Namespace="RDAIBServiceSpace")]
    public partial class RDAIBService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SOAPHeaderHandleIB sOAPHeaderHandleIBValueField;
        
        private System.Threading.SendOrPostCallback USER_CheckLoginNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_CheckCompanyNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Index_OtherFinancial_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Index_ReferenceValue_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Investmentbank_Index_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Investmentbank_CWBB_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback ZTProject_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback YIGZProject_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SZWTInitOperationCompleted;
        
        private System.Threading.SendOrPostCallback JKSCInitOperationCompleted;
        
        private System.Threading.SendOrPostCallback THGZ_OpeOperationCompleted;
        
        private System.Threading.SendOrPostCallback TXProCondiInitOperationCompleted;
        
        private System.Threading.SendOrPostCallback TXProject_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback gettradingOperationCompleted;
        
        private System.Threading.SendOrPostCallback getenterpriseOperationCompleted;
        
        private System.Threading.SendOrPostCallback FuFeiOperationCompleted;
        
        private System.Threading.SendOrPostCallback THGZ_AddOperationCompleted;
        
        private System.Threading.SendOrPostCallback JXProject_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsFuFeiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RDAIBService() {
            this.Url = global::billrda.Properties.Settings.Default.billrda_RDA_TH_RDAIBService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SOAPHeaderHandleIB SOAPHeaderHandleIBValue {
            get {
                return this.sOAPHeaderHandleIBValueField;
            }
            set {
                this.sOAPHeaderHandleIBValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event USER_CheckLoginNameCompletedEventHandler USER_CheckLoginNameCompleted;
        
        /// <remarks/>
        public event USER_CheckCompanyNameCompletedEventHandler USER_CheckCompanyNameCompleted;
        
        /// <remarks/>
        public event USER_RegisterCompletedEventHandler USER_RegisterCompleted;
        
        /// <remarks/>
        public event USER_LoginCompletedEventHandler USER_LoginCompleted;
        
        /// <remarks/>
        public event Index_OtherFinancial_DataCompletedEventHandler Index_OtherFinancial_DataCompleted;
        
        /// <remarks/>
        public event Index_ReferenceValue_DataCompletedEventHandler Index_ReferenceValue_DataCompleted;
        
        /// <remarks/>
        public event Investmentbank_Index_DataCompletedEventHandler Investmentbank_Index_DataCompleted;
        
        /// <remarks/>
        public event Investmentbank_CWBB_DataCompletedEventHandler Investmentbank_CWBB_DataCompleted;
        
        /// <remarks/>
        public event ZTProject_ListCompletedEventHandler ZTProject_ListCompleted;
        
        /// <remarks/>
        public event YIGZProject_ListCompletedEventHandler YIGZProject_ListCompleted;
        
        /// <remarks/>
        public event SZWTInitCompletedEventHandler SZWTInitCompleted;
        
        /// <remarks/>
        public event JKSCInitCompletedEventHandler JKSCInitCompleted;
        
        /// <remarks/>
        public event THGZ_OpeCompletedEventHandler THGZ_OpeCompleted;
        
        /// <remarks/>
        public event TXProCondiInitCompletedEventHandler TXProCondiInitCompleted;
        
        /// <remarks/>
        public event TXProject_ListCompletedEventHandler TXProject_ListCompleted;
        
        /// <remarks/>
        public event gettradingCompletedEventHandler gettradingCompleted;
        
        /// <remarks/>
        public event getenterpriseCompletedEventHandler getenterpriseCompleted;
        
        /// <remarks/>
        public event FuFeiCompletedEventHandler FuFeiCompleted;
        
        /// <remarks/>
        public event THGZ_AddCompletedEventHandler THGZ_AddCompleted;
        
        /// <remarks/>
        public event JXProject_ListCompletedEventHandler JXProject_ListCompleted;
        
        /// <remarks/>
        public event IsFuFeiCompletedEventHandler IsFuFeiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/USER_CheckLoginName", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_CheckLoginName(string param) {
            object[] results = this.Invoke("USER_CheckLoginName", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_CheckLoginNameAsync(string param) {
            this.USER_CheckLoginNameAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_CheckLoginNameAsync(string param, object userState) {
            if ((this.USER_CheckLoginNameOperationCompleted == null)) {
                this.USER_CheckLoginNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_CheckLoginNameOperationCompleted);
            }
            this.InvokeAsync("USER_CheckLoginName", new object[] {
                        param}, this.USER_CheckLoginNameOperationCompleted, userState);
        }
        
        private void OnUSER_CheckLoginNameOperationCompleted(object arg) {
            if ((this.USER_CheckLoginNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_CheckLoginNameCompleted(this, new USER_CheckLoginNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/USER_CheckCompanyName", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_CheckCompanyName(string param) {
            object[] results = this.Invoke("USER_CheckCompanyName", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_CheckCompanyNameAsync(string param) {
            this.USER_CheckCompanyNameAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_CheckCompanyNameAsync(string param, object userState) {
            if ((this.USER_CheckCompanyNameOperationCompleted == null)) {
                this.USER_CheckCompanyNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_CheckCompanyNameOperationCompleted);
            }
            this.InvokeAsync("USER_CheckCompanyName", new object[] {
                        param}, this.USER_CheckCompanyNameOperationCompleted, userState);
        }
        
        private void OnUSER_CheckCompanyNameOperationCompleted(object arg) {
            if ((this.USER_CheckCompanyNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_CheckCompanyNameCompleted(this, new USER_CheckCompanyNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/USER_Register", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_Register(string param) {
            object[] results = this.Invoke("USER_Register", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_RegisterAsync(string param) {
            this.USER_RegisterAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_RegisterAsync(string param, object userState) {
            if ((this.USER_RegisterOperationCompleted == null)) {
                this.USER_RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_RegisterOperationCompleted);
            }
            this.InvokeAsync("USER_Register", new object[] {
                        param}, this.USER_RegisterOperationCompleted, userState);
        }
        
        private void OnUSER_RegisterOperationCompleted(object arg) {
            if ((this.USER_RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_RegisterCompleted(this, new USER_RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/USER_Login", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_Login(string param) {
            object[] results = this.Invoke("USER_Login", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_LoginAsync(string param) {
            this.USER_LoginAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_LoginAsync(string param, object userState) {
            if ((this.USER_LoginOperationCompleted == null)) {
                this.USER_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_LoginOperationCompleted);
            }
            this.InvokeAsync("USER_Login", new object[] {
                        param}, this.USER_LoginOperationCompleted, userState);
        }
        
        private void OnUSER_LoginOperationCompleted(object arg) {
            if ((this.USER_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_LoginCompleted(this, new USER_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/Index_OtherFinancial_Data", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Index_OtherFinancial_Data(string param) {
            object[] results = this.Invoke("Index_OtherFinancial_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Index_OtherFinancial_DataAsync(string param) {
            this.Index_OtherFinancial_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Index_OtherFinancial_DataAsync(string param, object userState) {
            if ((this.Index_OtherFinancial_DataOperationCompleted == null)) {
                this.Index_OtherFinancial_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndex_OtherFinancial_DataOperationCompleted);
            }
            this.InvokeAsync("Index_OtherFinancial_Data", new object[] {
                        param}, this.Index_OtherFinancial_DataOperationCompleted, userState);
        }
        
        private void OnIndex_OtherFinancial_DataOperationCompleted(object arg) {
            if ((this.Index_OtherFinancial_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Index_OtherFinancial_DataCompleted(this, new Index_OtherFinancial_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/Index_ReferenceValue_Data", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Index_ReferenceValue_Data(string param) {
            object[] results = this.Invoke("Index_ReferenceValue_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Index_ReferenceValue_DataAsync(string param) {
            this.Index_ReferenceValue_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Index_ReferenceValue_DataAsync(string param, object userState) {
            if ((this.Index_ReferenceValue_DataOperationCompleted == null)) {
                this.Index_ReferenceValue_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndex_ReferenceValue_DataOperationCompleted);
            }
            this.InvokeAsync("Index_ReferenceValue_Data", new object[] {
                        param}, this.Index_ReferenceValue_DataOperationCompleted, userState);
        }
        
        private void OnIndex_ReferenceValue_DataOperationCompleted(object arg) {
            if ((this.Index_ReferenceValue_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Index_ReferenceValue_DataCompleted(this, new Index_ReferenceValue_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/Investmentbank_Index_Data", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Investmentbank_Index_Data(string param) {
            object[] results = this.Invoke("Investmentbank_Index_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Investmentbank_Index_DataAsync(string param) {
            this.Investmentbank_Index_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Investmentbank_Index_DataAsync(string param, object userState) {
            if ((this.Investmentbank_Index_DataOperationCompleted == null)) {
                this.Investmentbank_Index_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvestmentbank_Index_DataOperationCompleted);
            }
            this.InvokeAsync("Investmentbank_Index_Data", new object[] {
                        param}, this.Investmentbank_Index_DataOperationCompleted, userState);
        }
        
        private void OnInvestmentbank_Index_DataOperationCompleted(object arg) {
            if ((this.Investmentbank_Index_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Investmentbank_Index_DataCompleted(this, new Investmentbank_Index_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/Investmentbank_CWBB_Data", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Investmentbank_CWBB_Data(string param) {
            object[] results = this.Invoke("Investmentbank_CWBB_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Investmentbank_CWBB_DataAsync(string param) {
            this.Investmentbank_CWBB_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Investmentbank_CWBB_DataAsync(string param, object userState) {
            if ((this.Investmentbank_CWBB_DataOperationCompleted == null)) {
                this.Investmentbank_CWBB_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInvestmentbank_CWBB_DataOperationCompleted);
            }
            this.InvokeAsync("Investmentbank_CWBB_Data", new object[] {
                        param}, this.Investmentbank_CWBB_DataOperationCompleted, userState);
        }
        
        private void OnInvestmentbank_CWBB_DataOperationCompleted(object arg) {
            if ((this.Investmentbank_CWBB_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Investmentbank_CWBB_DataCompleted(this, new Investmentbank_CWBB_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/ZTProject_List", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ZTProject_List(string param) {
            object[] results = this.Invoke("ZTProject_List", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ZTProject_ListAsync(string param) {
            this.ZTProject_ListAsync(param, null);
        }
        
        /// <remarks/>
        public void ZTProject_ListAsync(string param, object userState) {
            if ((this.ZTProject_ListOperationCompleted == null)) {
                this.ZTProject_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnZTProject_ListOperationCompleted);
            }
            this.InvokeAsync("ZTProject_List", new object[] {
                        param}, this.ZTProject_ListOperationCompleted, userState);
        }
        
        private void OnZTProject_ListOperationCompleted(object arg) {
            if ((this.ZTProject_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ZTProject_ListCompleted(this, new ZTProject_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/YIGZProject_List", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string YIGZProject_List(string param) {
            object[] results = this.Invoke("YIGZProject_List", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void YIGZProject_ListAsync(string param) {
            this.YIGZProject_ListAsync(param, null);
        }
        
        /// <remarks/>
        public void YIGZProject_ListAsync(string param, object userState) {
            if ((this.YIGZProject_ListOperationCompleted == null)) {
                this.YIGZProject_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnYIGZProject_ListOperationCompleted);
            }
            this.InvokeAsync("YIGZProject_List", new object[] {
                        param}, this.YIGZProject_ListOperationCompleted, userState);
        }
        
        private void OnYIGZProject_ListOperationCompleted(object arg) {
            if ((this.YIGZProject_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.YIGZProject_ListCompleted(this, new YIGZProject_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/SZWTInit", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SZWTInit() {
            object[] results = this.Invoke("SZWTInit", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SZWTInitAsync() {
            this.SZWTInitAsync(null);
        }
        
        /// <remarks/>
        public void SZWTInitAsync(object userState) {
            if ((this.SZWTInitOperationCompleted == null)) {
                this.SZWTInitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSZWTInitOperationCompleted);
            }
            this.InvokeAsync("SZWTInit", new object[0], this.SZWTInitOperationCompleted, userState);
        }
        
        private void OnSZWTInitOperationCompleted(object arg) {
            if ((this.SZWTInitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SZWTInitCompleted(this, new SZWTInitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/JKSCInit", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JKSCInit() {
            object[] results = this.Invoke("JKSCInit", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JKSCInitAsync() {
            this.JKSCInitAsync(null);
        }
        
        /// <remarks/>
        public void JKSCInitAsync(object userState) {
            if ((this.JKSCInitOperationCompleted == null)) {
                this.JKSCInitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJKSCInitOperationCompleted);
            }
            this.InvokeAsync("JKSCInit", new object[0], this.JKSCInitOperationCompleted, userState);
        }
        
        private void OnJKSCInitOperationCompleted(object arg) {
            if ((this.JKSCInitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JKSCInitCompleted(this, new JKSCInitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/THGZ_Ope", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string THGZ_Ope(string param) {
            object[] results = this.Invoke("THGZ_Ope", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void THGZ_OpeAsync(string param) {
            this.THGZ_OpeAsync(param, null);
        }
        
        /// <remarks/>
        public void THGZ_OpeAsync(string param, object userState) {
            if ((this.THGZ_OpeOperationCompleted == null)) {
                this.THGZ_OpeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTHGZ_OpeOperationCompleted);
            }
            this.InvokeAsync("THGZ_Ope", new object[] {
                        param}, this.THGZ_OpeOperationCompleted, userState);
        }
        
        private void OnTHGZ_OpeOperationCompleted(object arg) {
            if ((this.THGZ_OpeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.THGZ_OpeCompleted(this, new THGZ_OpeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/TXProCondiInit", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TXProCondiInit(string param) {
            object[] results = this.Invoke("TXProCondiInit", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TXProCondiInitAsync(string param) {
            this.TXProCondiInitAsync(param, null);
        }
        
        /// <remarks/>
        public void TXProCondiInitAsync(string param, object userState) {
            if ((this.TXProCondiInitOperationCompleted == null)) {
                this.TXProCondiInitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTXProCondiInitOperationCompleted);
            }
            this.InvokeAsync("TXProCondiInit", new object[] {
                        param}, this.TXProCondiInitOperationCompleted, userState);
        }
        
        private void OnTXProCondiInitOperationCompleted(object arg) {
            if ((this.TXProCondiInitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TXProCondiInitCompleted(this, new TXProCondiInitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/TXProject_List", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TXProject_List(string param) {
            object[] results = this.Invoke("TXProject_List", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TXProject_ListAsync(string param) {
            this.TXProject_ListAsync(param, null);
        }
        
        /// <remarks/>
        public void TXProject_ListAsync(string param, object userState) {
            if ((this.TXProject_ListOperationCompleted == null)) {
                this.TXProject_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTXProject_ListOperationCompleted);
            }
            this.InvokeAsync("TXProject_List", new object[] {
                        param}, this.TXProject_ListOperationCompleted, userState);
        }
        
        private void OnTXProject_ListOperationCompleted(object arg) {
            if ((this.TXProject_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TXProject_ListCompleted(this, new TXProject_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/gettrading", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string gettrading(string param) {
            object[] results = this.Invoke("gettrading", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void gettradingAsync(string param) {
            this.gettradingAsync(param, null);
        }
        
        /// <remarks/>
        public void gettradingAsync(string param, object userState) {
            if ((this.gettradingOperationCompleted == null)) {
                this.gettradingOperationCompleted = new System.Threading.SendOrPostCallback(this.OngettradingOperationCompleted);
            }
            this.InvokeAsync("gettrading", new object[] {
                        param}, this.gettradingOperationCompleted, userState);
        }
        
        private void OngettradingOperationCompleted(object arg) {
            if ((this.gettradingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.gettradingCompleted(this, new gettradingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/getenterprise", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getenterprise(string param) {
            object[] results = this.Invoke("getenterprise", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getenterpriseAsync(string param) {
            this.getenterpriseAsync(param, null);
        }
        
        /// <remarks/>
        public void getenterpriseAsync(string param, object userState) {
            if ((this.getenterpriseOperationCompleted == null)) {
                this.getenterpriseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetenterpriseOperationCompleted);
            }
            this.InvokeAsync("getenterprise", new object[] {
                        param}, this.getenterpriseOperationCompleted, userState);
        }
        
        private void OngetenterpriseOperationCompleted(object arg) {
            if ((this.getenterpriseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getenterpriseCompleted(this, new getenterpriseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/FuFei", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FuFei(string param) {
            object[] results = this.Invoke("FuFei", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FuFeiAsync(string param) {
            this.FuFeiAsync(param, null);
        }
        
        /// <remarks/>
        public void FuFeiAsync(string param, object userState) {
            if ((this.FuFeiOperationCompleted == null)) {
                this.FuFeiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFuFeiOperationCompleted);
            }
            this.InvokeAsync("FuFei", new object[] {
                        param}, this.FuFeiOperationCompleted, userState);
        }
        
        private void OnFuFeiOperationCompleted(object arg) {
            if ((this.FuFeiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FuFeiCompleted(this, new FuFeiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/THGZ_Add", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string THGZ_Add(string param) {
            object[] results = this.Invoke("THGZ_Add", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void THGZ_AddAsync(string param) {
            this.THGZ_AddAsync(param, null);
        }
        
        /// <remarks/>
        public void THGZ_AddAsync(string param, object userState) {
            if ((this.THGZ_AddOperationCompleted == null)) {
                this.THGZ_AddOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTHGZ_AddOperationCompleted);
            }
            this.InvokeAsync("THGZ_Add", new object[] {
                        param}, this.THGZ_AddOperationCompleted, userState);
        }
        
        private void OnTHGZ_AddOperationCompleted(object arg) {
            if ((this.THGZ_AddCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.THGZ_AddCompleted(this, new THGZ_AddCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/JXProject_List", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string JXProject_List(string param) {
            object[] results = this.Invoke("JXProject_List", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void JXProject_ListAsync(string param) {
            this.JXProject_ListAsync(param, null);
        }
        
        /// <remarks/>
        public void JXProject_ListAsync(string param, object userState) {
            if ((this.JXProject_ListOperationCompleted == null)) {
                this.JXProject_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnJXProject_ListOperationCompleted);
            }
            this.InvokeAsync("JXProject_List", new object[] {
                        param}, this.JXProject_ListOperationCompleted, userState);
        }
        
        private void OnJXProject_ListOperationCompleted(object arg) {
            if ((this.JXProject_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.JXProject_ListCompleted(this, new JXProject_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleIBValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAIBServiceSpace/IsFuFei", RequestNamespace="RDAIBServiceSpace", ResponseNamespace="RDAIBServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string IsFuFei(string param) {
            object[] results = this.Invoke("IsFuFei", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void IsFuFeiAsync(string param) {
            this.IsFuFeiAsync(param, null);
        }
        
        /// <remarks/>
        public void IsFuFeiAsync(string param, object userState) {
            if ((this.IsFuFeiOperationCompleted == null)) {
                this.IsFuFeiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsFuFeiOperationCompleted);
            }
            this.InvokeAsync("IsFuFei", new object[] {
                        param}, this.IsFuFeiOperationCompleted, userState);
        }
        
        private void OnIsFuFeiOperationCompleted(object arg) {
            if ((this.IsFuFeiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsFuFeiCompleted(this, new IsFuFeiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="RDAIBServiceSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="RDAIBServiceSpace", IsNullable=false)]
    public partial class SOAPHeaderHandleIB : System.Web.Services.Protocols.SoapHeader {
        
        private string curNameField;
        
        private string curPwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string CurName {
            get {
                return this.curNameField;
            }
            set {
                this.curNameField = value;
            }
        }
        
        /// <remarks/>
        public string CurPwd {
            get {
                return this.curPwdField;
            }
            set {
                this.curPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_CheckLoginNameCompletedEventHandler(object sender, USER_CheckLoginNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_CheckLoginNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_CheckLoginNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_CheckCompanyNameCompletedEventHandler(object sender, USER_CheckCompanyNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_CheckCompanyNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_CheckCompanyNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_RegisterCompletedEventHandler(object sender, USER_RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_LoginCompletedEventHandler(object sender, USER_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Index_OtherFinancial_DataCompletedEventHandler(object sender, Index_OtherFinancial_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Index_OtherFinancial_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Index_OtherFinancial_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Index_ReferenceValue_DataCompletedEventHandler(object sender, Index_ReferenceValue_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Index_ReferenceValue_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Index_ReferenceValue_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Investmentbank_Index_DataCompletedEventHandler(object sender, Investmentbank_Index_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Investmentbank_Index_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Investmentbank_Index_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Investmentbank_CWBB_DataCompletedEventHandler(object sender, Investmentbank_CWBB_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Investmentbank_CWBB_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Investmentbank_CWBB_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ZTProject_ListCompletedEventHandler(object sender, ZTProject_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ZTProject_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ZTProject_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void YIGZProject_ListCompletedEventHandler(object sender, YIGZProject_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class YIGZProject_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal YIGZProject_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SZWTInitCompletedEventHandler(object sender, SZWTInitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SZWTInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SZWTInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void JKSCInitCompletedEventHandler(object sender, JKSCInitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JKSCInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JKSCInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void THGZ_OpeCompletedEventHandler(object sender, THGZ_OpeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class THGZ_OpeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal THGZ_OpeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TXProCondiInitCompletedEventHandler(object sender, TXProCondiInitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TXProCondiInitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TXProCondiInitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void TXProject_ListCompletedEventHandler(object sender, TXProject_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TXProject_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TXProject_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void gettradingCompletedEventHandler(object sender, gettradingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class gettradingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal gettradingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getenterpriseCompletedEventHandler(object sender, getenterpriseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getenterpriseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getenterpriseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void FuFeiCompletedEventHandler(object sender, FuFeiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FuFeiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FuFeiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void THGZ_AddCompletedEventHandler(object sender, THGZ_AddCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class THGZ_AddCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal THGZ_AddCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void JXProject_ListCompletedEventHandler(object sender, JXProject_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JXProject_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal JXProject_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void IsFuFeiCompletedEventHandler(object sender, IsFuFeiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsFuFeiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsFuFeiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591