//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1 版自动生成。
// 
#pragma warning disable 1591

namespace RDA_Web.RDA {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RDAWebServiceSoap", Namespace="RDAWebServiceSpace")]
    public partial class RDAWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private SOAPHeaderHandle sOAPHeaderHandleValueField;
        
        private System.Threading.SendOrPostCallback USER_CheckLoginNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_CheckCompanyNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_RegisterOperationCompleted;
        
        private System.Threading.SendOrPostCallback USER_LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback Index_OtherFinancial_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Index_ReferenceValue_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Index_KeyFinancial_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_Assets_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_Profit_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Report_CashFlow_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreditReport_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Risk_Count_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Risk_Report_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Trading_ListOperationCompleted;
        
        private System.Threading.SendOrPostCallback Trading_Enum_DataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Enterprise_BasicDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback Trading_GetOperationCompleted;
        
        private System.Threading.SendOrPostCallback Trading_EditStepOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback Trading_EditStepTwoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RDAWebService() {
            this.Url = global::RDA_Web.Properties.Settings.Default.RDA_Web_RDA_RDAWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public SOAPHeaderHandle SOAPHeaderHandleValue {
            get {
                return this.sOAPHeaderHandleValueField;
            }
            set {
                this.sOAPHeaderHandleValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event USER_CheckLoginNameCompletedEventHandler USER_CheckLoginNameCompleted;
        
        /// <remarks/>
        public event USER_CheckCompanyNameCompletedEventHandler USER_CheckCompanyNameCompleted;
        
        /// <remarks/>
        public event USER_RegisterCompletedEventHandler USER_RegisterCompleted;
        
        /// <remarks/>
        public event USER_LoginCompletedEventHandler USER_LoginCompleted;
        
        /// <remarks/>
        public event Index_OtherFinancial_DataCompletedEventHandler Index_OtherFinancial_DataCompleted;
        
        /// <remarks/>
        public event Index_ReferenceValue_DataCompletedEventHandler Index_ReferenceValue_DataCompleted;
        
        /// <remarks/>
        public event Index_KeyFinancial_DataCompletedEventHandler Index_KeyFinancial_DataCompleted;
        
        /// <remarks/>
        public event Report_Assets_DataCompletedEventHandler Report_Assets_DataCompleted;
        
        /// <remarks/>
        public event Report_Profit_DataCompletedEventHandler Report_Profit_DataCompleted;
        
        /// <remarks/>
        public event Report_CashFlow_DataCompletedEventHandler Report_CashFlow_DataCompleted;
        
        /// <remarks/>
        public event CreditReport_DataCompletedEventHandler CreditReport_DataCompleted;
        
        /// <remarks/>
        public event Risk_Count_DataCompletedEventHandler Risk_Count_DataCompleted;
        
        /// <remarks/>
        public event Risk_Report_DataCompletedEventHandler Risk_Report_DataCompleted;
        
        /// <remarks/>
        public event Trading_ListCompletedEventHandler Trading_ListCompleted;
        
        /// <remarks/>
        public event Trading_Enum_DataCompletedEventHandler Trading_Enum_DataCompleted;
        
        /// <remarks/>
        public event Enterprise_BasicDataCompletedEventHandler Enterprise_BasicDataCompleted;
        
        /// <remarks/>
        public event Trading_GetCompletedEventHandler Trading_GetCompleted;
        
        /// <remarks/>
        public event Trading_EditStepOneCompletedEventHandler Trading_EditStepOneCompleted;
        
        /// <remarks/>
        public event Trading_EditStepTwoCompletedEventHandler Trading_EditStepTwoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/USER_CheckLoginName", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_CheckLoginName(string param) {
            object[] results = this.Invoke("USER_CheckLoginName", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_CheckLoginNameAsync(string param) {
            this.USER_CheckLoginNameAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_CheckLoginNameAsync(string param, object userState) {
            if ((this.USER_CheckLoginNameOperationCompleted == null)) {
                this.USER_CheckLoginNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_CheckLoginNameOperationCompleted);
            }
            this.InvokeAsync("USER_CheckLoginName", new object[] {
                        param}, this.USER_CheckLoginNameOperationCompleted, userState);
        }
        
        private void OnUSER_CheckLoginNameOperationCompleted(object arg) {
            if ((this.USER_CheckLoginNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_CheckLoginNameCompleted(this, new USER_CheckLoginNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/USER_CheckCompanyName", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_CheckCompanyName(string param) {
            object[] results = this.Invoke("USER_CheckCompanyName", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_CheckCompanyNameAsync(string param) {
            this.USER_CheckCompanyNameAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_CheckCompanyNameAsync(string param, object userState) {
            if ((this.USER_CheckCompanyNameOperationCompleted == null)) {
                this.USER_CheckCompanyNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_CheckCompanyNameOperationCompleted);
            }
            this.InvokeAsync("USER_CheckCompanyName", new object[] {
                        param}, this.USER_CheckCompanyNameOperationCompleted, userState);
        }
        
        private void OnUSER_CheckCompanyNameOperationCompleted(object arg) {
            if ((this.USER_CheckCompanyNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_CheckCompanyNameCompleted(this, new USER_CheckCompanyNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/USER_Register", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_Register(string param) {
            object[] results = this.Invoke("USER_Register", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_RegisterAsync(string param) {
            this.USER_RegisterAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_RegisterAsync(string param, object userState) {
            if ((this.USER_RegisterOperationCompleted == null)) {
                this.USER_RegisterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_RegisterOperationCompleted);
            }
            this.InvokeAsync("USER_Register", new object[] {
                        param}, this.USER_RegisterOperationCompleted, userState);
        }
        
        private void OnUSER_RegisterOperationCompleted(object arg) {
            if ((this.USER_RegisterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_RegisterCompleted(this, new USER_RegisterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/USER_Login", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string USER_Login(string param) {
            object[] results = this.Invoke("USER_Login", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void USER_LoginAsync(string param) {
            this.USER_LoginAsync(param, null);
        }
        
        /// <remarks/>
        public void USER_LoginAsync(string param, object userState) {
            if ((this.USER_LoginOperationCompleted == null)) {
                this.USER_LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUSER_LoginOperationCompleted);
            }
            this.InvokeAsync("USER_Login", new object[] {
                        param}, this.USER_LoginOperationCompleted, userState);
        }
        
        private void OnUSER_LoginOperationCompleted(object arg) {
            if ((this.USER_LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.USER_LoginCompleted(this, new USER_LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Index_OtherFinancial_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Index_OtherFinancial_Data(string param) {
            object[] results = this.Invoke("Index_OtherFinancial_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Index_OtherFinancial_DataAsync(string param) {
            this.Index_OtherFinancial_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Index_OtherFinancial_DataAsync(string param, object userState) {
            if ((this.Index_OtherFinancial_DataOperationCompleted == null)) {
                this.Index_OtherFinancial_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndex_OtherFinancial_DataOperationCompleted);
            }
            this.InvokeAsync("Index_OtherFinancial_Data", new object[] {
                        param}, this.Index_OtherFinancial_DataOperationCompleted, userState);
        }
        
        private void OnIndex_OtherFinancial_DataOperationCompleted(object arg) {
            if ((this.Index_OtherFinancial_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Index_OtherFinancial_DataCompleted(this, new Index_OtherFinancial_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Index_ReferenceValue_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Index_ReferenceValue_Data(string param) {
            object[] results = this.Invoke("Index_ReferenceValue_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Index_ReferenceValue_DataAsync(string param) {
            this.Index_ReferenceValue_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Index_ReferenceValue_DataAsync(string param, object userState) {
            if ((this.Index_ReferenceValue_DataOperationCompleted == null)) {
                this.Index_ReferenceValue_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndex_ReferenceValue_DataOperationCompleted);
            }
            this.InvokeAsync("Index_ReferenceValue_Data", new object[] {
                        param}, this.Index_ReferenceValue_DataOperationCompleted, userState);
        }
        
        private void OnIndex_ReferenceValue_DataOperationCompleted(object arg) {
            if ((this.Index_ReferenceValue_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Index_ReferenceValue_DataCompleted(this, new Index_ReferenceValue_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Index_KeyFinancial_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Index_KeyFinancial_Data(string param) {
            object[] results = this.Invoke("Index_KeyFinancial_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Index_KeyFinancial_DataAsync(string param) {
            this.Index_KeyFinancial_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Index_KeyFinancial_DataAsync(string param, object userState) {
            if ((this.Index_KeyFinancial_DataOperationCompleted == null)) {
                this.Index_KeyFinancial_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIndex_KeyFinancial_DataOperationCompleted);
            }
            this.InvokeAsync("Index_KeyFinancial_Data", new object[] {
                        param}, this.Index_KeyFinancial_DataOperationCompleted, userState);
        }
        
        private void OnIndex_KeyFinancial_DataOperationCompleted(object arg) {
            if ((this.Index_KeyFinancial_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Index_KeyFinancial_DataCompleted(this, new Index_KeyFinancial_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Report_Assets_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Report_Assets_Data(string param) {
            object[] results = this.Invoke("Report_Assets_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Report_Assets_DataAsync(string param) {
            this.Report_Assets_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Report_Assets_DataAsync(string param, object userState) {
            if ((this.Report_Assets_DataOperationCompleted == null)) {
                this.Report_Assets_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_Assets_DataOperationCompleted);
            }
            this.InvokeAsync("Report_Assets_Data", new object[] {
                        param}, this.Report_Assets_DataOperationCompleted, userState);
        }
        
        private void OnReport_Assets_DataOperationCompleted(object arg) {
            if ((this.Report_Assets_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_Assets_DataCompleted(this, new Report_Assets_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Report_Profit_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Report_Profit_Data(string param) {
            object[] results = this.Invoke("Report_Profit_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Report_Profit_DataAsync(string param) {
            this.Report_Profit_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Report_Profit_DataAsync(string param, object userState) {
            if ((this.Report_Profit_DataOperationCompleted == null)) {
                this.Report_Profit_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_Profit_DataOperationCompleted);
            }
            this.InvokeAsync("Report_Profit_Data", new object[] {
                        param}, this.Report_Profit_DataOperationCompleted, userState);
        }
        
        private void OnReport_Profit_DataOperationCompleted(object arg) {
            if ((this.Report_Profit_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_Profit_DataCompleted(this, new Report_Profit_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Report_CashFlow_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Report_CashFlow_Data(string param) {
            object[] results = this.Invoke("Report_CashFlow_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Report_CashFlow_DataAsync(string param) {
            this.Report_CashFlow_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Report_CashFlow_DataAsync(string param, object userState) {
            if ((this.Report_CashFlow_DataOperationCompleted == null)) {
                this.Report_CashFlow_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReport_CashFlow_DataOperationCompleted);
            }
            this.InvokeAsync("Report_CashFlow_Data", new object[] {
                        param}, this.Report_CashFlow_DataOperationCompleted, userState);
        }
        
        private void OnReport_CashFlow_DataOperationCompleted(object arg) {
            if ((this.Report_CashFlow_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Report_CashFlow_DataCompleted(this, new Report_CashFlow_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/CreditReport_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreditReport_Data(string param) {
            object[] results = this.Invoke("CreditReport_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreditReport_DataAsync(string param) {
            this.CreditReport_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void CreditReport_DataAsync(string param, object userState) {
            if ((this.CreditReport_DataOperationCompleted == null)) {
                this.CreditReport_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreditReport_DataOperationCompleted);
            }
            this.InvokeAsync("CreditReport_Data", new object[] {
                        param}, this.CreditReport_DataOperationCompleted, userState);
        }
        
        private void OnCreditReport_DataOperationCompleted(object arg) {
            if ((this.CreditReport_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreditReport_DataCompleted(this, new CreditReport_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Risk_Count_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Risk_Count_Data(string param) {
            object[] results = this.Invoke("Risk_Count_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Risk_Count_DataAsync(string param) {
            this.Risk_Count_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Risk_Count_DataAsync(string param, object userState) {
            if ((this.Risk_Count_DataOperationCompleted == null)) {
                this.Risk_Count_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRisk_Count_DataOperationCompleted);
            }
            this.InvokeAsync("Risk_Count_Data", new object[] {
                        param}, this.Risk_Count_DataOperationCompleted, userState);
        }
        
        private void OnRisk_Count_DataOperationCompleted(object arg) {
            if ((this.Risk_Count_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Risk_Count_DataCompleted(this, new Risk_Count_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Risk_Report_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Risk_Report_Data(string param) {
            object[] results = this.Invoke("Risk_Report_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Risk_Report_DataAsync(string param) {
            this.Risk_Report_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Risk_Report_DataAsync(string param, object userState) {
            if ((this.Risk_Report_DataOperationCompleted == null)) {
                this.Risk_Report_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRisk_Report_DataOperationCompleted);
            }
            this.InvokeAsync("Risk_Report_Data", new object[] {
                        param}, this.Risk_Report_DataOperationCompleted, userState);
        }
        
        private void OnRisk_Report_DataOperationCompleted(object arg) {
            if ((this.Risk_Report_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Risk_Report_DataCompleted(this, new Risk_Report_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Trading_List", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Trading_List(string param) {
            object[] results = this.Invoke("Trading_List", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Trading_ListAsync(string param) {
            this.Trading_ListAsync(param, null);
        }
        
        /// <remarks/>
        public void Trading_ListAsync(string param, object userState) {
            if ((this.Trading_ListOperationCompleted == null)) {
                this.Trading_ListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrading_ListOperationCompleted);
            }
            this.InvokeAsync("Trading_List", new object[] {
                        param}, this.Trading_ListOperationCompleted, userState);
        }
        
        private void OnTrading_ListOperationCompleted(object arg) {
            if ((this.Trading_ListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Trading_ListCompleted(this, new Trading_ListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Trading_Enum_Data", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Trading_Enum_Data(string param) {
            object[] results = this.Invoke("Trading_Enum_Data", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Trading_Enum_DataAsync(string param) {
            this.Trading_Enum_DataAsync(param, null);
        }
        
        /// <remarks/>
        public void Trading_Enum_DataAsync(string param, object userState) {
            if ((this.Trading_Enum_DataOperationCompleted == null)) {
                this.Trading_Enum_DataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrading_Enum_DataOperationCompleted);
            }
            this.InvokeAsync("Trading_Enum_Data", new object[] {
                        param}, this.Trading_Enum_DataOperationCompleted, userState);
        }
        
        private void OnTrading_Enum_DataOperationCompleted(object arg) {
            if ((this.Trading_Enum_DataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Trading_Enum_DataCompleted(this, new Trading_Enum_DataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Enterprise_BasicData", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Enterprise_BasicData(string param) {
            object[] results = this.Invoke("Enterprise_BasicData", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Enterprise_BasicDataAsync(string param) {
            this.Enterprise_BasicDataAsync(param, null);
        }
        
        /// <remarks/>
        public void Enterprise_BasicDataAsync(string param, object userState) {
            if ((this.Enterprise_BasicDataOperationCompleted == null)) {
                this.Enterprise_BasicDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnterprise_BasicDataOperationCompleted);
            }
            this.InvokeAsync("Enterprise_BasicData", new object[] {
                        param}, this.Enterprise_BasicDataOperationCompleted, userState);
        }
        
        private void OnEnterprise_BasicDataOperationCompleted(object arg) {
            if ((this.Enterprise_BasicDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Enterprise_BasicDataCompleted(this, new Enterprise_BasicDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Trading_Get", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Trading_Get(string param) {
            object[] results = this.Invoke("Trading_Get", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Trading_GetAsync(string param) {
            this.Trading_GetAsync(param, null);
        }
        
        /// <remarks/>
        public void Trading_GetAsync(string param, object userState) {
            if ((this.Trading_GetOperationCompleted == null)) {
                this.Trading_GetOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrading_GetOperationCompleted);
            }
            this.InvokeAsync("Trading_Get", new object[] {
                        param}, this.Trading_GetOperationCompleted, userState);
        }
        
        private void OnTrading_GetOperationCompleted(object arg) {
            if ((this.Trading_GetCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Trading_GetCompleted(this, new Trading_GetCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Trading_EditStepOne", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Trading_EditStepOne(string param) {
            object[] results = this.Invoke("Trading_EditStepOne", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Trading_EditStepOneAsync(string param) {
            this.Trading_EditStepOneAsync(param, null);
        }
        
        /// <remarks/>
        public void Trading_EditStepOneAsync(string param, object userState) {
            if ((this.Trading_EditStepOneOperationCompleted == null)) {
                this.Trading_EditStepOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrading_EditStepOneOperationCompleted);
            }
            this.InvokeAsync("Trading_EditStepOne", new object[] {
                        param}, this.Trading_EditStepOneOperationCompleted, userState);
        }
        
        private void OnTrading_EditStepOneOperationCompleted(object arg) {
            if ((this.Trading_EditStepOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Trading_EditStepOneCompleted(this, new Trading_EditStepOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("SOAPHeaderHandleValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("RDAWebServiceSpace/Trading_EditStepTwo", RequestNamespace="RDAWebServiceSpace", ResponseNamespace="RDAWebServiceSpace", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Trading_EditStepTwo(string param) {
            object[] results = this.Invoke("Trading_EditStepTwo", new object[] {
                        param});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Trading_EditStepTwoAsync(string param) {
            this.Trading_EditStepTwoAsync(param, null);
        }
        
        /// <remarks/>
        public void Trading_EditStepTwoAsync(string param, object userState) {
            if ((this.Trading_EditStepTwoOperationCompleted == null)) {
                this.Trading_EditStepTwoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrading_EditStepTwoOperationCompleted);
            }
            this.InvokeAsync("Trading_EditStepTwo", new object[] {
                        param}, this.Trading_EditStepTwoOperationCompleted, userState);
        }
        
        private void OnTrading_EditStepTwoOperationCompleted(object arg) {
            if ((this.Trading_EditStepTwoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Trading_EditStepTwoCompleted(this, new Trading_EditStepTwoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="RDAWebServiceSpace")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="RDAWebServiceSpace", IsNullable=false)]
    public partial class SOAPHeaderHandle : System.Web.Services.Protocols.SoapHeader {
        
        private string curNameField;
        
        private string curPwdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string CurName {
            get {
                return this.curNameField;
            }
            set {
                this.curNameField = value;
            }
        }
        
        /// <remarks/>
        public string CurPwd {
            get {
                return this.curPwdField;
            }
            set {
                this.curPwdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_CheckLoginNameCompletedEventHandler(object sender, USER_CheckLoginNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_CheckLoginNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_CheckLoginNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_CheckCompanyNameCompletedEventHandler(object sender, USER_CheckCompanyNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_CheckCompanyNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_CheckCompanyNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_RegisterCompletedEventHandler(object sender, USER_RegisterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void USER_LoginCompletedEventHandler(object sender, USER_LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class USER_LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal USER_LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Index_OtherFinancial_DataCompletedEventHandler(object sender, Index_OtherFinancial_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Index_OtherFinancial_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Index_OtherFinancial_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Index_ReferenceValue_DataCompletedEventHandler(object sender, Index_ReferenceValue_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Index_ReferenceValue_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Index_ReferenceValue_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Index_KeyFinancial_DataCompletedEventHandler(object sender, Index_KeyFinancial_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Index_KeyFinancial_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Index_KeyFinancial_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Report_Assets_DataCompletedEventHandler(object sender, Report_Assets_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_Assets_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_Assets_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Report_Profit_DataCompletedEventHandler(object sender, Report_Profit_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_Profit_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_Profit_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Report_CashFlow_DataCompletedEventHandler(object sender, Report_CashFlow_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Report_CashFlow_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Report_CashFlow_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CreditReport_DataCompletedEventHandler(object sender, CreditReport_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreditReport_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreditReport_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Risk_Count_DataCompletedEventHandler(object sender, Risk_Count_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Risk_Count_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Risk_Count_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Risk_Report_DataCompletedEventHandler(object sender, Risk_Report_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Risk_Report_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Risk_Report_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Trading_ListCompletedEventHandler(object sender, Trading_ListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Trading_ListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Trading_ListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Trading_Enum_DataCompletedEventHandler(object sender, Trading_Enum_DataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Trading_Enum_DataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Trading_Enum_DataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Enterprise_BasicDataCompletedEventHandler(object sender, Enterprise_BasicDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Enterprise_BasicDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Enterprise_BasicDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Trading_GetCompletedEventHandler(object sender, Trading_GetCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Trading_GetCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Trading_GetCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Trading_EditStepOneCompletedEventHandler(object sender, Trading_EditStepOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Trading_EditStepOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Trading_EditStepOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Trading_EditStepTwoCompletedEventHandler(object sender, Trading_EditStepTwoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Trading_EditStepTwoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Trading_EditStepTwoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591